task:
  target: cell_types

head:
  output_dim: 39
  num_hidden_layers: 0

backbone:
  morph_encoder_name: vit_small_patch16_224
  expr_encoder_name: null
  fusion_strategy: null
  global_pool: token
  freeze_morph_encoder: false

data:
  name: beat
  batch_size: 512
  metadata_path: splits/default.parquet
  panel_path: default.yaml

lit:
  target_key: metadata.cell_type_target
  lr_head: 1.0e-4
  lr_backbone: 1.0e-5

wandb:
  project: debug

trainer:
  max_time: 00:01:45:00
  max_epochs: 35
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
