artifacts:
  name: owkin
  data_dir: /work/PRTNR/CHUV/DIR/rgottar1/spatial/data/mesothelioma/xenium-hne-fusion-v4
  cell_type_col: first_type
  tile_px: 512
  stride_px: 256
  items:
    name: g_cells
    filter:
      organs: null
      include_ids:
        - CH_G_532a_x2
        - CH_G_533a_x2
        - CH_G_534a_x1
        - CH_G_535a_x2
#        - CH_G_535a_xr
        - CH_G_536a_x2
      exclude_ids: null
      num_transcripts: 1000
      num_unique_transcripts: null
      num_cells: 10
      num_unique_cells: 5
  split:
    name: g_cells
    path: splits/owkin.yaml
  panel:
    name: g_cells
