project: xe-hne-fus-expr-v0
output_dir: figures/eval/hescape-breast-expression
filters:
  target: expression
  name: hest1k
  items_path: all.json
  metadata_paths:
    - hescape/breast/outer=0-seed=0.parquet
    - hescape/breast/outer=1-seed=0.parquet
    - hescape/breast/outer=2-seed=0.parquet
    - hescape/breast/outer=3-seed=0.parquet
    - hescape/breast/outer=4-seed=0.parquet
  panel_paths:
    - hescape/breast.yaml
baseline: vision
color_by_splits: false
