project: xe-hne-fus-expr-v0
output_dir: figures/eval/hescape-human-immuno-oncology-expression
filters:
  target: expression
  name: hest1k
  items_path: all.json
  metadata_paths:
    - hescape/human-immuno-oncology/outer=0-seed=0.parquet
    - hescape/human-immuno-oncology/outer=1-seed=0.parquet
    - hescape/human-immuno-oncology/outer=2-seed=0.parquet
    - hescape/human-immuno-oncology/outer=3-seed=0.parquet
    - hescape/human-immuno-oncology/outer=4-seed=0.parquet
  panel_paths:
    - hescape/human-immuno-oncology.yaml
baseline: vision
