project: xe-hne-fus-expr-v0
output_dir: figures/eval/hescape-lung-healthy-expression
filters:
  target: expression
  name: hest1k
  items_path: all.json
  metadata_paths:
    - hescape/lung-healthy/outer=0-seed=0.parquet
    - hescape/lung-healthy/outer=1-seed=0.parquet
    - hescape/lung-healthy/outer=2-seed=0.parquet
    - hescape/lung-healthy/outer=3-seed=0.parquet
    - hescape/lung-healthy/outer=4-seed=0.parquet
  panel_paths:
    - hescape/lung-healthy.yaml
baseline: vision
