task:
  target: cell_types

head:
  output_dim: 39
  num_hidden_layers: 0

backbone:
  morph_encoder_name: null
  morph_encoder_kws: null
  expr_encoder_name: mlp
  expr_encoder_kws:
    output_dim: 32
    num_hidden_layers: 1
    dropout: 0.1
  fusion_strategy: null
  fusion_stage: null
  use_proj: false
  learnable_gate: false
  global_pool: null

data:
  name: beat
  num_workers: 10
  batch_size: 256
  expr_pool: tile
  items_path: cells.json
  metadata_path: cells/outer=0-inner=0-seed=0.parquet
  panel_path: default.yaml

lit:
  target_key: target
  lr_head: 1.0e-4
  lr_backbone: 1.0e-5

wandb:
  project: xe-hne-fus-cell-v0
  name: expr-tile

trainer:
  max_time: 00:01:45:00
  max_epochs: 35
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0
