name: beat
items:
  name: all
  filter:
    organs: null
    include_ids: null
    exclude_ids: null
    num_transcripts: null
    num_unique_transcripts: null
    num_cells: null
    num_unique_cells: null

