name: xenium-hne-fusion-ray
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pip:
      - wandb
      - anndata
      - colorcet
      - glom
      - numpy
      - pandas
      - geopandas
      - huggingface-hub
      - jsonargparse
      - lazyslide
      - loguru
      - matplotlib
      - opencv-python
      - openslide-bin
      - openslide-python
      - pillow
      - pyarrow
      - ray
      - python-dotenv
      - pyyaml
      - scanpy
      - scikit-image
      - scikit-learn
      - scikit-misc
      - scipy
      - spatialdata
      - tiffslide
      - lightning==2.5.1.post0
      - torch==2.7.0
      - torchvision==0.22.0
      - torchmetrics==1.6.1
      - torchinfo
      - tqdm
      - wsidata
      - zarr
      - --extra-index-url https://download.pytorch.org/whl/cu128
