head:
  num_hidden_layers: 0

backbone:
  morph_encoder_name: null
  expr_encoder_name: mlp
  expr_encoder_kws:
    output_dim: 32
    num_hidden_layers: 1
    dropout: 0.1
  fusion_strategy: null
  global_pool: null
  expr_token_pool: avg

data:
  name: hest1k
  batch_size: 512
  expr_pool: token
  metadata_path: splits/default.parquet
  panel_path: default.yaml

lit:
  lr_head: 1e-4

wandb:
  project: debug

trainer:
  max_time: 00:01:45:00
  max_epochs: 35
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
